language: python

python:
  - 3.7-dev
  - 3.6-dev
  - 3.5
  - 3.4
  - 3.3
  - 2.7
  - 2.6

env:
  - DJANGO=2.1
  - DJANGO=2.0
  - DJANGO=1.11
  - DJANGO=1.10
  - DJANGO=1.9
  - DJANGO=1.8
  - DJANGO=1.7
  - DJANGO=1.6
  - DJANGO=1.5

install:
  - pip install -r "test_requirements/django-$DJANGO.txt"

before_script:
    - export CODACY_PROJECT_TOKEN=7b692e68ce0447dca28e27cb4944f35f

script:
  - pep8 fancy_cronfield
  - coverage run --branch --parallel-mode setup.py test
  - coverage combine
  - coverage xml -o coverage.xml

after_success:
  - codecov
  - python-codacy-coverage -r coverage.xml

notifications:
  irc:
    - irc.freenode.org#django-fancy-cronfield

matrix:
  exclude:
    - python: 2.6
      env: DJANGO=1.7
    - python: 2.6
      env: DJANGO=1.8
    - python: 2.6
      env: DJANGO=1.9
    - python: 2.6
      env: DJANGO=1.10
    - python: 2.6
      env: DJANGO=1.11
    - python: 2.6
      env: DJANGO=2.0
    - python: 2.6
      env: DJANGO=2.1

    - python: 2.7
      env: DJANGO=2.0
    - python: 2.7
      env: DJANGO=2.1

    - python: 3.3
      env: DJANGO=1.9
    - python: 3.3
      env: DJANGO=1.10
    - python: 3.3
      env: DJANGO=1.11
    - python: 3.3
      env: DJANGO=2.0
    - python: 3.3
      env: DJANGO=2.1

    - python: 3.4
      env: DJANGO=2.1

    - python: 3.5
      env: DJANGO=1.5
    - python: 3.5
      env: DJANGO=1.6
    - python: 3.5
      env: DJANGO=1.7

    - python: 3.6-dev
      env: DJANGO=1.5
    - python: 3.6-dev
      env: DJANGO=1.6
    - python: 3.6-dev
      env: DJANGO=1.7

    - python: 3.7-dev
      env: DJANGO=1.5
    - python: 3.7-dev
      env: DJANGO=1.6
    - python: 3.7-dev
      env: DJANGO=1.7
